name: dukan_dost
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  uuid: ^4.5.1
  http: ^1.5.0
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  photo_view: ^0.15.0
  cached_network_image: ^3.4.1
  flutter_screenutil: ^5.9.3
  flash: ^3.1.1
  dio: ^5.9.0
  shimmer_animation: ^2.2.2
  flutter_launcher_icons: ^0.14.4
  google_fonts: ^6.3.2
#  cupertino_icons: ^1.0.2
#  get: ^4.6.5
#  uuid: ^4.2.2
#  http: ^1.1.0
#  shared_preferences: ^2.2.2
#  intl: ^0.19.0
#  photo_view: ^0.15.0
#  cached_network_image: ^3.3.1
#  flutter_screenutil: ^5.9.3
#  flash: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/dd_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat-BlackItalic.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat-ExtraBoldItalic.ttf
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/Montserrat-ExtraLightItalic.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-LightItalic.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
        - asset: assets/fonts/Montserrat-Thin.ttf
        - asset: assets/fonts/Montserrat-ThinItalic.ttf
        - asset: assets/fonts/Montserrat-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/Montserrat-VariableFont_wght.ttf    
